"""
Export the data-derived INLP per-SDG sample target n_target as a num_*.tex macro.

Reads the register_adjust checkpoint (2_data/3b_register/{slug}/{track}/
checkpoint.json) and emits \RegisterIterNPerSdg from its recorded
config.n_target. This replaces the retired fixed constant (previously 1000):
n_target is the global minimum over all (SDG, corpus) of available counts and
is snapshot-dependent, so it must come from the JSON record, not a constant.

CHEAP BY DESIGN: only reads the checkpoint that register_adjust.py already
persisted. Does not re-run INLP or any analysis stage. Fingerprint-gated.

Reads:
  2_data/3b_register/{slug}/{track}/checkpoint.json  -> config.n_target
Writes:
  4_outputs/{model}/tables/num12c_register_ntarget.tex
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[3]
CODE_ROOT = ROOT / "1_code"
SHARED_DIR = Path(__file__).resolve().parents[0]
for path in (CODE_ROOT, SHARED_DIR):
    if str(path) not in sys.path:
        sys.path.insert(0, str(path))

from model_utils import DEFAULT_EMBED_MODEL, resolve_model_alias
from register_utils import register_dir, track_for_model
from shared_utils import (
    ensure_canonical_outputs,
    fingerprint_of,
    record_fingerprint,
    should_skip,
)
from shard_pipeline_utils import load_json


def run(model: str, output_dir: Path, overwrite: bool = False) -> None:
    outs = ensure_canonical_outputs(output_dir, model=model)
    track = track_for_model(model)
    ckpt_path = register_dir(model, track) / "checkpoint.json"

    if not ckpt_path.exists():
        raise FileNotFoundError(
            f"Register checkpoint not found at {ckpt_path}. "
            "Run the register_adjust stage (INLP) first."
        )

    ckpt = load_json(ckpt_path)
    n_target = (ckpt.get("config") or {}).get("n_target")
    if n_target is None:
        raise ValueError(f"No config.n_target in {ckpt_path}")

    primary = outs.tables_dir / "num12c_register_ntarget.tex"
    outputs = [primary]
    fp = fingerprint_of(ckpt_path) + "v1"
    if should_skip(outputs, fp, overwrite, primary):
        print(f"Skipping {primary} — inputs unchanged")
        return

    lines = [
        "% Auto-generated by g_register_ntarget_macro.py — reads the register_adjust "
        "checkpoint; do not edit manually",
        rf"\newcommand{{\RegisterIterNPerSdg}}{{{n_target}}}",
    ]
    primary.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"Written {primary} (n_target={n_target})")
    record_fingerprint(outputs, fp, primary)


def parse_args(argv=None):
    parser = argparse.ArgumentParser(
        description="Export the data-derived INLP n_target as a tex macro."
    )
    parser.add_argument("--embed-model", default=DEFAULT_EMBED_MODEL, type=resolve_model_alias)
    parser.add_argument("--output-dir", default=str(ROOT / "4_outputs"))
    parser.add_argument("--overwrite", action="store_true", help=argparse.SUPPRESS)
    return parser.parse_args(argv)


def main():
    args = parse_args()
    run(args.embed_model, Path(args.output_dir), overwrite=args.overwrite)


if __name__ == "__main__":
    main()
