"""
Consolidated macro generator for the register-topic decomposition (plan §6.6).

Reads the restructure JSONs (decomposition, interaction extension) and writes
ALL new num_*.tex macros.  Run LAST after all JSONs exist.

Inputs:
  4_outputs/{model}/data/register_decomposition.json
  4_outputs/{model}/data/interaction_extended.json

Outputs:
  4_outputs/{model}/tables/num5_register_decomposition.tex  (consolidated macros)

Run from project root:
  python 1_code/7_main_analysis/0_shared/generate_tex_macros.py --embed-model mpnet
"""

from __future__ import annotations

import argparse
import logging
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[3]
CODE_ROOT = ROOT / "1_code"
ANALYSIS_ROOT = Path(__file__).resolve().parents[1]
SHARED_DIR = ANALYSIS_ROOT / "0_shared"
for path in (CODE_ROOT, SHARED_DIR):
    if str(path) not in sys.path:
        sys.path.insert(0, str(path))

from model_utils import DEFAULT_EMBED_MODEL, SDG_NUM_WORDS, resolve_model_alias
from shared_utils import ensure_canonical_outputs, fingerprint_of, should_skip, record_fingerprint
from shard_pipeline_utils import load_json

logging.basicConfig(level=logging.INFO, format="%(levelname)s  %(message)s")
log = logging.getLogger(__name__)


def parse_args() -> argparse.Namespace:
    p = argparse.ArgumentParser(description="Consolidated tex macro generator for register-topic decomposition.")
    p.add_argument("--output-dir", default=str(ROOT / "4_outputs"))
    p.add_argument("--embed-model", default=DEFAULT_EMBED_MODEL, type=resolve_model_alias, help=argparse.SUPPRESS)
    p.add_argument("--overwrite", action="store_true", help=argparse.SUPPRESS)
    return p.parse_args()


def run(args: argparse.Namespace) -> None:
    model = args.embed_model
    layout = ensure_canonical_outputs(Path(args.output_dir), model=model)
    data_dir = layout.data_dir
    tables_dir = layout.tables_dir

    decomp_path = data_dir / "register_decomposition.json"
    interaction_path = data_dir / "interaction_extended.json"
    out_tex = tables_dir / "num5_register_decomposition.tex"

    if not decomp_path.exists() or not interaction_path.exists():
        log.warning("Required JSONs not found — skipping macro generation.")
        log.info("  Checked: %s", decomp_path)
        log.info("  Checked: %s", interaction_path)
        return

    # ---- Fingerprint ----
    fp = fingerprint_of(decomp_path, interaction_path) + "macros_v1"
    if should_skip([out_tex], fp, args.overwrite, out_tex):
        log.info("Skipping macros — inputs unchanged")
        return

    # ---- Load data ----
    decomp = load_json(decomp_path)
    interaction = load_json(interaction_path)

    # ---- Build macros ----
    lines = [
        "% Auto-generated by generate_tex_macros.py — do not edit manually",
        "% Register-topic decomposition macros",
        "",
    ]

    # Decomposition summary
    summary = decomp["summary"]
    lines.append(rf"\newcommand{{\MeanRawGap}}{{{summary['mean_raw_gap']:.3f}}}")
    lines.append(rf"\newcommand{{\MeanAdjustedGap}}{{{summary['mean_adjusted_gap']:.3f}}}")
    lines.append(rf"\newcommand{{\MeanRegisterComponent}}{{{summary['mean_register_component']:.3f}}}")

    # Correlation headline
    corr = decomp["correlations"]
    if corr["coverage_vs_adjusted"]["rho"] is not None:
        lines.append(rf"\newcommand{{\RhoCovTopic}}{{{corr['coverage_vs_adjusted']['rho']:.3f}}}")
        if corr["coverage_vs_adjusted"].get("p") is not None:
            lines.append(rf"\newcommand{{\RhoCovTopicP}}{{{corr['coverage_vs_adjusted']['p']:.3f}}}")
    if corr["coverage_vs_register"]["rho"] is not None:
        lines.append(rf"\newcommand{{\RhoCovRegister}}{{{corr['coverage_vs_register']['rho']:.3f}}}")
        if corr["coverage_vs_register"].get("p") is not None:
            lines.append(rf"\newcommand{{\RhoCovRegisterP}}{{{corr['coverage_vs_register']['p']:.3f}}}")

    # Interaction headline (Spearman)
    h = interaction["headline"]
    lines.append(rf"\newcommand{{\SpearmanCovRaw}}{{{h['coverage_vs_raw_gap']['spearman_rho']:.3f}}}")
    lines.append(rf"\newcommand{{\SpearmanCovRawP}}{{{h['coverage_vs_raw_gap']['spearman_p']:.3f}}}")
    lines.append(rf"\newcommand{{\SpearmanCovAdj}}{{{h['coverage_vs_adjusted_gap']['spearman_rho']:.3f}}}")
    lines.append(rf"\newcommand{{\SpearmanCovAdjP}}{{{h['coverage_vs_adjusted_gap']['spearman_p']:.3f}}}")
    lines.append(rf"\newcommand{{\SpearmanCovReg}}{{{h['coverage_vs_register_component']['spearman_rho']:.3f}}}")
    lines.append(rf"\newcommand{{\SpearmanCovRegP}}{{{h['coverage_vs_register_component']['spearman_p']:.3f}}}")

    # Per-SDG decomposition values
    for r in decomp["per_sdg"]:
        sdg = r["sdg"]
        word = SDG_NUM_WORDS[sdg]
        if r["raw_gap"] is not None:
            lines.append(rf"\newcommand{{\RawGapSdg{word}}}{{{r['raw_gap']:.3f}}}")
        if r["adjusted_gap"] is not None:
            lines.append(rf"\newcommand{{\AdjGapSdg{word}}}{{{r['adjusted_gap']:.3f}}}")
        if r["register_component"] is not None:
            lines.append(rf"\newcommand{{\RegCompSdg{word}}}{{{r['register_component']:+.3f}}}")

    # ---- Write ----
    tables_dir.mkdir(parents=True, exist_ok=True)
    out_tex.write_text("\n".join(lines) + "\n", encoding="utf-8")
    log.info("Saved: %s", out_tex)
    record_fingerprint([out_tex], fp, out_tex)
    log.info("Consolidated macros complete (%d lines).", len(lines))


def main() -> None:
    run(parse_args())


if __name__ == "__main__":
    main()
