#!/usr/bin/env python3
"""
Fetch full-text PDFs of papers cited in the dissertation.

Inputs:
  - data/cited_papers.json   (generated by fetch_cited_papers.py)
  - writing/references.bib   (source bibliography)

Outputs:
  - literature/cited_papers/<key>.pdf     (downloaded PDFs)
  - literature/cited_papers/fetch_log.json (per-paper fetch status)

Strategy (in order of preference):
  1. ArXiv papers: direct PDF from https://arxiv.org/pdf/<id>
  2. Journal articles with DOI: Semantic Scholar API openAccessPdf field
  3. Fallback: Unpaywall API (requires email, tried second)
  4. Skip items without a fetchable source (datasets, books, GitHub repos)

Run: python3 code/fetch_full_papers.py

Notes:
  - Only open-access PDFs are fetched (no paywalled content)
  - Reports/datasets (UN2015, SDGi2024, etc.) have no PDF to fetch — skipped
  - Gibbons1994 is a book — skipped
  - Mejia2025 has no DOI yet (conference proceedings) — skipped
  - Re-running is safe: skips already-downloaded files
"""

import json
import os
import sys
import time
from pathlib import Path

try:
    import requests
except ImportError:
    os.system("pip install requests")
    import requests

SEMANTIC_SCHOLAR_API = "https://api.semanticscholar.org/graph/v1/paper"
UNPAYWALL_EMAIL = "qmanhbeo@gmail.com"  # required by Unpaywall TOS

# Papers where we know no PDF is fetchable (skip silently)
SKIP_KEYS = {
    "SDGBenchmark",   # GitHub repo, not a paper
    "Gibbons1994",    # Book — no open-access PDF
    "SDGi2024",       # HuggingFace dataset
    "UNGDC2024",      # Harvard Dataverse dataset
    "UN2015",         # UN resolution (HTML only on UN website)
    "Paris2015",      # UN treaty document
    "IPCC2022",       # IPCC report (large, not a paper)
    "OECD2019",       # OECD web document
    "EUAI2024",       # EU legislation
    "UNESCO2021",     # UNESCO recommendation
    "UKAI2021",       # UK government document
    "UNAI2024",       # UN advisory report
    "AUAI2024",       # AU continental strategy
    "Sachs2024",      # SDSN report
    "Sachs2025",      # SDSN report
    "Mejia2025",      # No DOI yet
}


def load_citations(json_path: Path) -> list[dict]:
    with open(json_path) as f:
        return json.load(f)


def fetch_arxiv_pdf(arxiv_id: str, out_path: Path) -> bool:
    """Download PDF from arXiv."""
    # arXiv provides direct PDF links
    url = f"https://arxiv.org/pdf/{arxiv_id}"
    print(f"  → arXiv: {url}")
    try:
        r = requests.get(url, timeout=30, headers={"User-Agent": "Mozilla/5.0"})
        if r.status_code == 200 and r.headers.get("Content-Type", "").startswith("application/pdf"):
            out_path.write_bytes(r.content)
            return True
        print(f"  ✗ arXiv returned {r.status_code} or non-PDF")
    except Exception as e:
        print(f"  ✗ arXiv error: {e}")
    return False


def fetch_semantic_scholar(doi: str) -> str | None:
    """Query Semantic Scholar for open-access PDF URL."""
    url = f"{SEMANTIC_SCHOLAR_API}/DOI:{doi}?fields=openAccessPdf,externalIds"
    try:
        r = requests.get(url, timeout=10, headers={"User-Agent": "Mozilla/5.0"})
        if r.status_code == 200:
            data = r.json()
            oa = data.get("openAccessPdf")
            if oa and oa.get("url"):
                return oa["url"]
    except Exception as e:
        print(f"  ✗ Semantic Scholar error: {e}")
    return None


def fetch_unpaywall(doi: str) -> str | None:
    """Query Unpaywall for open-access PDF URL."""
    url = f"https://api.unpaywall.org/v2/{doi}?email={UNPAYWALL_EMAIL}"
    try:
        r = requests.get(url, timeout=10)
        if r.status_code == 200:
            data = r.json()
            best = data.get("best_oa_location")
            if best and best.get("url_for_pdf"):
                return best["url_for_pdf"]
            # Try any OA location
            for loc in data.get("oa_locations", []):
                if loc.get("url_for_pdf"):
                    return loc["url_for_pdf"]
    except Exception as e:
        print(f"  ✗ Unpaywall error: {e}")
    return None


def download_pdf(url: str, out_path: Path) -> bool:
    """Download a PDF from a URL."""
    try:
        r = requests.get(url, timeout=30, headers={"User-Agent": "Mozilla/5.0"}, allow_redirects=True)
        if r.status_code == 200:
            content_type = r.headers.get("Content-Type", "")
            if "pdf" in content_type or r.content[:4] == b"%PDF":
                out_path.write_bytes(r.content)
                size_kb = len(r.content) // 1024
                print(f"  ✓ Downloaded {size_kb} KB")
                return True
            else:
                print(f"  ✗ Not a PDF (Content-Type: {content_type[:60]})")
        else:
            print(f"  ✗ HTTP {r.status_code}")
    except Exception as e:
        print(f"  ✗ Download error: {e}")
    return False


def fetch_paper(paper: dict, out_dir: Path) -> dict:
    """Attempt to fetch the full-text PDF of a paper. Returns status dict."""
    key = paper["key"]
    doi = paper.get("doi")
    eprint = paper.get("eprint")
    out_path = out_dir / f"{key}.pdf"

    result = {"key": key, "title": paper["title"], "status": "skipped", "pdf_path": None, "source": None}

    if key in SKIP_KEYS:
        result["status"] = "skipped_no_pdf"
        result["reason"] = "Not a journal/conference paper or known non-OA"
        return result

    if out_path.exists():
        result["status"] = "already_exists"
        result["pdf_path"] = str(out_path)
        return result

    print(f"\n[{key}] {paper['title'][:70]}...")

    # Strategy 1: arXiv direct
    if eprint:
        if fetch_arxiv_pdf(eprint, out_path):
            result.update({"status": "ok", "pdf_path": str(out_path), "source": f"arxiv:{eprint}"})
            return result
        time.sleep(1)

    if not doi:
        result["status"] = "no_doi"
        result["reason"] = "No DOI available"
        return result

    # Strategy 2: Semantic Scholar open-access PDF
    print(f"  → Semantic Scholar (DOI: {doi})")
    ss_url = fetch_semantic_scholar(doi)
    if ss_url:
        print(f"  → OA PDF from Semantic Scholar: {ss_url[:80]}")
        if download_pdf(ss_url, out_path):
            result.update({"status": "ok", "pdf_path": str(out_path), "source": f"semantic_scholar"})
            return result
    time.sleep(0.5)

    # Strategy 3: Unpaywall
    print(f"  → Unpaywall (DOI: {doi})")
    uw_url = fetch_unpaywall(doi)
    if uw_url:
        print(f"  → OA PDF from Unpaywall: {uw_url[:80]}")
        if download_pdf(uw_url, out_path):
            result.update({"status": "ok", "pdf_path": str(out_path), "source": "unpaywall"})
            return result
    time.sleep(0.5)

    result["status"] = "not_found_oa"
    result["reason"] = "No open-access PDF found via Semantic Scholar or Unpaywall"
    return result


def convert_with_marker(pdf_path: Path, md_dir: Path, marker_dir: Path) -> bool:
    """Convert a PDF to markdown using marker."""
    md_path = md_dir / (pdf_path.stem + ".md")
    if md_path.exists():
        return True

    convert_script = marker_dir / "convert_single.py"
    if not convert_script.exists():
        print(f"  ✗ marker convert_single.py not found at {convert_script}")
        return False

    cmd = f"cd {marker_dir} && python convert_single.py '{pdf_path}' --output_dir '{md_dir}' 2>&1"
    ret = os.system(cmd)
    return ret == 0


def main():
    repo_root = Path(__file__).parent.parent
    citations_json = repo_root / "data" / "cited_papers.json"
    out_dir = repo_root / "literature" / "cited_papers"
    marker_dir = repo_root / "marker"

    if not citations_json.exists():
        print("Run fetch_cited_papers.py first to generate data/cited_papers.json")
        sys.exit(1)

    out_dir.mkdir(parents=True, exist_ok=True)

    papers = load_citations(citations_json)
    print(f"Found {len(papers)} citations. Fetching open-access PDFs...\n")

    log = []
    ok = skipped = failed = 0

    for paper in papers:
        result = fetch_paper(paper, out_dir)
        log.append(result)

        if result["status"] == "ok":
            ok += 1
        elif result["status"].startswith("skipped") or result["status"] == "already_exists":
            skipped += 1
        else:
            failed += 1

    # Write fetch log
    log_path = out_dir / "fetch_log.json"
    with open(log_path, "w") as f:
        json.dump(log, f, indent=2)

    # Summary
    print(f"\n{'='*60}")
    print(f"FETCH COMPLETE: {ok} downloaded, {skipped} skipped, {failed} not available as OA")
    print(f"\nResults:")
    for r in log:
        icon = {"ok": "✓", "already_exists": "=", "skipped_no_pdf": "—", "not_found_oa": "✗", "no_doi": "?"}.get(r["status"], "?")
        print(f"  {icon} [{r['key']}] {r['status']}")

    print(f"\nLog: {log_path.relative_to(repo_root)}")
    print(f"PDFs: {out_dir.relative_to(repo_root)}/")

    # Convert downloaded PDFs using marker
    fetched_pdfs = [Path(r["pdf_path"]) for r in log if r["status"] == "ok" and r["pdf_path"]]
    if fetched_pdfs and marker_dir.exists():
        md_dir = repo_root / "literature" / "cited_papers_md"
        md_dir.mkdir(exist_ok=True)
        print(f"\nConverting {len(fetched_pdfs)} PDFs to Markdown with marker...")

        # Check if marker dependencies are installed
        try:
            import marker  # noqa
            marker_available = True
        except ImportError:
            marker_available = False

        if not marker_available:
            print("  marker Python package not installed. To convert PDFs:")
            print(f"    cd {marker_dir}")
            print("    pip install -e .")
            print(f"    python convert.py '{out_dir}' --output_dir '{md_dir}'")
        else:
            for pdf_path in fetched_pdfs:
                print(f"  Converting {pdf_path.name}...")
                convert_with_marker(pdf_path, md_dir, marker_dir)
    elif fetched_pdfs:
        print(f"\nNote: marker not found at {marker_dir}. Convert PDFs manually:")
        print(f"  git clone https://github.com/datalab-to/marker.git marker")
        print(f"  cd marker && pip install -e .")
        print(f"  python convert.py '{out_dir}' --output_dir 'literature/cited_papers_md'")


if __name__ == "__main__":
    main()
