#!/usr/bin/env python3
"""Regenerate the manuscript's conceptual LaTeX figures (fig1, fig6).

These are hand-authored TikZ diagrams living in this folder
(``fig_conceptual_framework.tex``, ``fig_pipeline_flowchart.tex``), compiled
standalone with ``pdflatex``. They are model-independent, so they are emitted
once into ``4_outputs/conceptual_figs/`` rather than a model-namespaced dir.

Idempotent: a figure is skipped when its PDF already exists and the source
``.tex`` has not been modified since. Pass ``--overwrite`` to force a recompile.
"""
from __future__ import annotations

import argparse
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
SRC_DIR = Path(__file__).resolve().parent
OUT_DIR = ROOT / "4_outputs" / "conceptual_figs"

# source base name -> manuscript figure file name (without extension)
# fig6 (pipeline flowchart) is now generated by build_pipeline_flowchart.py
# (matplotlib) rather than a hand-authored TikZ diagram.
FIGURES = {
    "fig_conceptual_framework": "fig1_conceptual_framework",
}


def _needs_build(src: Path, out_pdf: Path, out_png: Path, overwrite: bool) -> bool:
    if overwrite or not out_pdf.exists() or not out_png.exists():
        return True
    return src.stat().st_mtime > out_pdf.stat().st_mtime


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument(
        "--overwrite", action="store_true",
        help="Recompile even if the PDF exists and is up to date.",
    )
    args = ap.parse_args()

    OUT_DIR.mkdir(parents=True, exist_ok=True)
    rc = 0

    # fig6 pipeline flowchart is generated via matplotlib (not TikZ).
    try:
        if str(SRC_DIR) not in sys.path:
            sys.path.insert(0, str(SRC_DIR))
        from build_pipeline_flowchart import build as build_pipeline_flowchart
        rc |= build_pipeline_flowchart(overwrite=args.overwrite)
    except Exception as exc:  # pragma: no cover - defensive
        print(f"[conceptual-figs] FAILED to build pipeline flowchart: {exc}", file=sys.stderr)
        rc = 1

    for src_base, jobname in FIGURES.items():
        src = SRC_DIR / f"{src_base}.tex"
        out_pdf = OUT_DIR / f"{jobname}.pdf"
        out_png = OUT_DIR / f"{jobname}.png"
        if not src.exists():
            print(f"[conceptual-figs] SKIP {src_base}: source {src} missing", file=sys.stderr)
            continue
        if not _needs_build(src, out_pdf, out_png, args.overwrite):
            print(f"[conceptual-figs] UP-TO-DATE {jobname}.pdf + .png")
            continue
        print(f"[conceptual-figs] Building {jobname}.pdf from {src.name}")
        try:
            subprocess.run(
                [
                    "pdflatex", "-interaction=nonstopmode", "-halt-on-error",
                    "-jobname", jobname,
                    "-output-directory", str(OUT_DIR), str(src),
                ],
                cwd=str(SRC_DIR), check=True,
            )
            # Convert PDF to PNG at 300 DPI (matches matplotlib figures).
            print(f"[conceptual-figs] Exporting {jobname}.png at 300 DPI")
            subprocess.run(
                ["pdftoppm", "-png", "-r", "300", str(out_pdf), str(out_png.with_suffix(""))],
                check=True,
            )
            # pdftoppm outputs <name>-1.png; rename to <name>.png
            produced = Path(f"{out_png.with_suffix('')}-1.png")
            if produced.exists():
                produced.rename(out_png)
        except subprocess.CalledProcessError as exc:
            print(f"[conceptual-figs] FAILED to build {jobname}: {exc}", file=sys.stderr)
            rc = 1
        finally:
            # Clean auxiliary files; the PDF and PNG (if produced) are kept.
            for ext in (".aux", ".log", ".out"):
                aux = OUT_DIR / f"{jobname}{ext}"
                if aux.exists():
                    aux.unlink()
    return rc


if __name__ == "__main__":
    raise SystemExit(main())
