"""
SDG 17 sparse-reference sensitivity diagnostic.

This appendix-stage diagnostic probes how sensitive the SDG 17 headline result is to the
fact that its reference centroid is built from only 31 expert-labelled benchmark texts,
rather than from the larger OSDG reference corpus used for SDGs 1--16.

Method:
  1. Bootstrap the 31 SDG 17 benchmark texts with replacement.
  2. Rebuild only the SDG 17 centroid for each resample.
  3. Re-score only the SDG 17 column against fixed scores for the other 16 SDGs.
  4. Reconstruct the SDG 17 research and policy clusters induced by that resampled centroid.
  5. Recompute the resulting SDG 17 within-goal semantic gap.

This is a conditional reference-set sensitivity check, not a formal inferential confidence
interval over substantive SDG 17 reality.

Run from project root:
    python code/3_main_analysis/3_appendix/6_sdg17_reference_sensitivity.py
"""

from __future__ import annotations

import argparse
import csv
import json
import logging
import sys
from pathlib import Path
from typing import Any

import numpy as np

ROOT = Path(__file__).resolve().parents[3]
CODE_ROOT = ROOT / "code"
ANALYSIS_ROOT = Path(__file__).resolve().parents[1]
SHARED_DIR = ANALYSIS_ROOT / "0_shared"
for path in (CODE_ROOT, SHARED_DIR):
    if str(path) not in sys.path:
        sys.path.insert(0, str(path))

from shared_utils import ensure_canonical_outputs, require_output_files
from semantic_gap_shared import (
    CHUNK_CAP_PRIMARY,
    MIN_CLUSTER_SIZE,
    POLICY_EMB,
    POLICY_IDS,
    POLICY_SCORES,
    RANDOM_SEED,
    build_sub_centroid,
    cap_policy_indices_per_doc,
)


DEFAULT_OUTPUT_ROOT = Path("outputs")
BENCHMARK_EMB = Path("data/2_embedded/benchmark.npy")
BENCHMARK_IDS = Path("data/2_embedded/metadata/benchmark_ids.json")
SDG_CENTROIDS = Path("data/3_scored/sdg_centroids.npy")
RESEARCH_SCORE_MANIFEST = Path("data/3_scored/paper_scores_shards/metadata/manifest.json")
RESEARCH_EMBED_MANIFEST = Path("data/2_embedded/research_shards/metadata/manifest.json")

OUTPUT_SUBDIR = "sdg17_sensitivity"
DRAWS_CSV = "sdg17_reference_bootstrap_draws.csv"
SUMMARY_JSON = "sdg17_reference_bootstrap_summary.json"
NUM_TEX = "num_sdg17_reference_sensitivity.tex"
TABLE_TEX = "tab_sdg17_reference_sensitivity.tex"

SDG17 = 17
SDG17_IDX = SDG17 - 1
DEFAULT_DRAWS = 200
DEFAULT_BLOCK_SIZE = 50

logging.basicConfig(level=logging.INFO, format="%(levelname)s  %(message)s")
log = logging.getLogger(__name__)


def parse_args() -> argparse.Namespace:
    p = argparse.ArgumentParser(description="Run SDG 17 sparse-reference sensitivity diagnostic.")
    p.add_argument("--output-dir", default=str(DEFAULT_OUTPUT_ROOT))
    p.add_argument("--draws", type=int, default=DEFAULT_DRAWS)
    p.add_argument("--seed", type=int, default=RANDOM_SEED)
    p.add_argument("--block-size", type=int, default=DEFAULT_BLOCK_SIZE)
    return p.parse_args()


def load_json(path: Path) -> Any:
    with path.open(encoding="utf-8") as f:
        return json.load(f)


def pctile(values: np.ndarray, q: float) -> float:
    return float(np.percentile(values, q))


def format_pct(value: float) -> str:
    return f"{value:.3f}"


def format_int(value: int) -> str:
    return f"{value:,}"


def write_csv(path: Path, fieldnames: list[str], rows: list[dict[str, Any]]) -> None:
    with path.open("w", encoding="utf-8", newline="") as f:
        writer = csv.DictWriter(f, fieldnames=fieldnames)
        writer.writeheader()
        writer.writerows(rows)


def write_num_tex(path: Path, summary: dict[str, Any]) -> None:
    lines = [
        "% Auto-generated by code/3_main_analysis/3_appendix/6_sdg17_reference_sensitivity.py — do not edit manually",
        rf"\newcommand{{\SdgSeventeenBenchmarkN}}{{{format_int(int(summary['benchmark_n']))}}}",
        rf"\newcommand{{\SdgSeventeenBootstrapDraws}}{{{format_int(int(summary['draws']))}}}",
        rf"\newcommand{{\SdgSeventeenBaselineGap}}{{{format_pct(float(summary['baseline']['semantic_gap']))}}}",
        rf"\newcommand{{\SdgSeventeenBootstrapCosineMedian}}{{{format_pct(float(summary['bootstrap']['centroid_cosine_to_baseline']['median']))}}}",
        rf"\newcommand{{\SdgSeventeenBootstrapCosinePFive}}{{{format_pct(float(summary['bootstrap']['centroid_cosine_to_baseline']['p05']))}}}",
        rf"\newcommand{{\SdgSeventeenBootstrapCosinePNinetyFive}}{{{format_pct(float(summary['bootstrap']['centroid_cosine_to_baseline']['p95']))}}}",
        rf"\newcommand{{\SdgSeventeenBootstrapGapMedian}}{{{format_pct(float(summary['bootstrap']['semantic_gap']['median']))}}}",
        rf"\newcommand{{\SdgSeventeenBootstrapGapPFive}}{{{format_pct(float(summary['bootstrap']['semantic_gap']['p05']))}}}",
        rf"\newcommand{{\SdgSeventeenBootstrapGapPNinetyFive}}{{{format_pct(float(summary['bootstrap']['semantic_gap']['p95']))}}}",
        rf"\newcommand{{\SdgSeventeenBootstrapResearchMedian}}{{{format_int(int(summary['bootstrap']['n_research_papers']['median']))}}}",
        rf"\newcommand{{\SdgSeventeenBootstrapResearchPFive}}{{{format_int(int(summary['bootstrap']['n_research_papers']['p05']))}}}",
        rf"\newcommand{{\SdgSeventeenBootstrapResearchPNinetyFive}}{{{format_int(int(summary['bootstrap']['n_research_papers']['p95']))}}}",
        rf"\newcommand{{\SdgSeventeenBootstrapPolicyDocsMedian}}{{{format_int(int(summary['bootstrap']['n_policy_docs_capped']['median']))}}}",
        rf"\newcommand{{\SdgSeventeenBootstrapPolicyDocsPFive}}{{{format_int(int(summary['bootstrap']['n_policy_docs_capped']['p05']))}}}",
        rf"\newcommand{{\SdgSeventeenBootstrapPolicyDocsPNinetyFive}}{{{format_int(int(summary['bootstrap']['n_policy_docs_capped']['p95']))}}}",
    ]
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def write_table(path: Path, summary: dict[str, Any]) -> None:
    baseline = summary["baseline"]
    bootstrap = summary["bootstrap"]
    lines = [
        "% Auto-generated by code/3_main_analysis/3_appendix/6_sdg17_reference_sensitivity.py — do not edit manually",
        r"\begin{tabular}{p{4.0cm}p{8.8cm}}",
        r"\toprule",
        r"Metric & Value \\",
        r"\midrule",
        rf"Baseline SDG 17 benchmark support & {format_int(int(summary['benchmark_n']))} expert-labelled texts from the SDG Classification Benchmark. \\",
        rf"Canonical SDG 17 semantic gap & {format_pct(float(baseline['semantic_gap']))}; research cluster {format_int(int(baseline['n_research_papers']))} papers, policy cluster {format_int(int(baseline['n_policy_docs_capped']))} capped source documents. \\",
        rf"Bootstrap centroid vs baseline & Median cosine {format_pct(float(bootstrap['centroid_cosine_to_baseline']['median']))}; 5th--95th percentile {format_pct(float(bootstrap['centroid_cosine_to_baseline']['p05']))}--{format_pct(float(bootstrap['centroid_cosine_to_baseline']['p95']))}. \\",
        rf"Bootstrap SDG 17 semantic gap & Median {format_pct(float(bootstrap['semantic_gap']['median']))}; 5th--95th percentile {format_pct(float(bootstrap['semantic_gap']['p05']))}--{format_pct(float(bootstrap['semantic_gap']['p95']))}. \\",
        rf"Bootstrap research cluster size & Median {format_int(int(bootstrap['n_research_papers']['median']))} papers; 5th--95th percentile {format_int(int(bootstrap['n_research_papers']['p05']))}--{format_int(int(bootstrap['n_research_papers']['p95']))}. \\",
        rf"Bootstrap policy cluster size & Median {format_int(int(bootstrap['n_policy_docs_capped']['median']))} capped source documents; 5th--95th percentile {format_int(int(bootstrap['n_policy_docs_capped']['p05']))}--{format_int(int(bootstrap['n_policy_docs_capped']['p95']))}. \\",
        r"\bottomrule",
        r"\end{tabular}",
    ]
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def resolve_manifest_data_path(stored_path: str) -> Path:
    raw = Path(stored_path)
    if raw.is_absolute():
        return raw
    return ROOT / raw


def load_aligned_research_shards() -> list[dict[str, Path | int]]:
    score_manifest = load_json(RESEARCH_SCORE_MANIFEST)
    emb_manifest = load_json(RESEARCH_EMBED_MANIFEST)
    score_shards = {int(row["shard_id"]): row for row in score_manifest["shards"]}
    emb_shards = {int(row["shard_id"]): row for row in emb_manifest["shards"]}
    shard_ids = sorted(score_shards)
    if shard_ids != sorted(emb_shards):
        raise RuntimeError("Research score shard IDs do not align with research embedding shard IDs.")
    aligned = []
    for shard_id in shard_ids:
        score_row = score_shards[shard_id]
        emb_row = emb_shards[shard_id]
        aligned.append(
            {
                "shard_id": shard_id,
                "score_path": resolve_manifest_data_path(str(score_row["score_path"])),
                "embedding_path": resolve_manifest_data_path(str(emb_row["embedding_path"])),
            }
        )
    return aligned


def bootstrap_reference_weights(
    *,
    ref_embeddings: np.ndarray,
    baseline_unit: np.ndarray,
    draws: int,
    seed: int,
) -> tuple[np.ndarray, np.ndarray]:
    rng = np.random.default_rng(seed)
    n_ref = ref_embeddings.shape[0]
    counts = rng.multinomial(n_ref, np.full(n_ref, 1.0 / n_ref), size=draws).astype(np.float32)
    raw = counts @ ref_embeddings.astype(np.float32)
    norms = np.linalg.norm(raw, axis=1)
    if np.any(norms < 1e-8):
        raise RuntimeError("Encountered near-zero bootstrap centroid norm for SDG 17.")
    weights = (counts / norms[:, None]).astype(np.float32)
    centroid_cos = (raw / norms[:, None]) @ baseline_unit.astype(np.float32)
    return weights, centroid_cos.astype(np.float32)


def aggregate_research_sdg17_clusters(
    *,
    shards: list[dict[str, Path | int]],
    ref_embeddings: np.ndarray,
    weights: np.ndarray,
    block_size: int,
) -> tuple[np.ndarray, np.ndarray]:
    draws = weights.shape[0]
    dim = ref_embeddings.shape[1]
    sums = np.zeros((draws, dim), dtype=np.float64)
    counts = np.zeros(draws, dtype=np.int64)

    for shard_idx, shard in enumerate(shards, start=1):
        emb = np.load(shard["embedding_path"]).astype(np.float32)
        score = np.load(shard["score_path"]).astype(np.float32)
        other_max = score[:, :SDG17_IDX].max(axis=1)
        projections = emb @ ref_embeddings.T

        for start in range(0, draws, block_size):
            stop = min(start + block_size, draws)
            block_weights = weights[start:stop].T
            new_scores = projections @ block_weights
            mask = new_scores > other_max[:, None]
            counts[start:stop] += mask.sum(axis=0).astype(np.int64)
            sums[start:stop] += mask.astype(np.float32).T @ emb

        log.info("Processed research shard %s/%s for SDG 17 bootstrap sensitivity", shard_idx, len(shards))

    return sums, counts


def compute_policy_rows(
    *,
    ref_embeddings: np.ndarray,
    weights: np.ndarray,
    policy_emb: np.ndarray,
    policy_scores: np.ndarray,
    policy_ids: list[dict[str, Any]],
    research_units: np.ndarray,
    research_counts: np.ndarray,
    seed: int,
) -> list[dict[str, Any]]:
    other_max = policy_scores[:, :SDG17_IDX].max(axis=1)
    projections = policy_emb @ ref_embeddings.T
    rows: list[dict[str, Any]] = []

    for draw_idx, weight in enumerate(weights):
        new_scores = projections @ weight
        assigned = np.flatnonzero(new_scores > other_max).tolist()
        rng = np.random.default_rng(seed + draw_idx)
        capped = cap_policy_indices_per_doc(assigned, policy_ids, CHUNK_CAP_PRIMARY, rng)
        raw_docs = {policy_ids[i]["source_doc"] for i in assigned}
        capped_docs = {policy_ids[i]["source_doc"] for i in capped}
        pol_centroid, pol_cohesion = build_sub_centroid(policy_emb, capped)
        unreliable = (
            int(research_counts[draw_idx]) < MIN_CLUSTER_SIZE
            or len(capped) < MIN_CLUSTER_SIZE
            or pol_centroid is None
        )
        if pol_centroid is None:
            semantic_similarity = None
            semantic_gap = None
        else:
            semantic_similarity = float(np.dot(research_units[draw_idx], pol_centroid))
            semantic_gap = 1.0 - semantic_similarity

        rows.append(
            {
                "draw": draw_idx + 1,
                "n_research_papers": int(research_counts[draw_idx]),
                "n_policy_chunks": len(assigned),
                "n_policy_chunks_capped": len(capped),
                "n_policy_docs": len(raw_docs),
                "n_policy_docs_capped": len(capped_docs),
                "semantic_similarity": None if semantic_similarity is None else round(semantic_similarity, 6),
                "semantic_gap": None if semantic_gap is None else round(semantic_gap, 6),
                "policy_cohesion": round(pol_cohesion, 6),
                "unreliable": bool(unreliable),
            }
        )

    return rows


def summarise_numeric(values: np.ndarray) -> dict[str, float | int]:
    return {
        "median": float(np.median(values)),
        "p05": pctile(values, 5),
        "p95": pctile(values, 95),
        "min": float(np.min(values)),
        "max": float(np.max(values)),
    }


def main() -> None:
    args = parse_args()
    if args.draws < 20:
        raise ValueError("--draws must be at least 20 for a stable appendix sensitivity summary.")
    if args.block_size < 1:
        raise ValueError("--block-size must be positive.")

    output_dir = Path(args.output_dir)
    layout = ensure_canonical_outputs(output_dir)
    require_output_files(layout.data_dir, ["sdg_conceptual_alignment_cosine_distances.json"])
    out_dir = output_dir / "appendix" / OUTPUT_SUBDIR
    out_dir.mkdir(parents=True, exist_ok=True)

    benchmark_emb = np.load(BENCHMARK_EMB).astype(np.float32)
    benchmark_ids = load_json(BENCHMARK_IDS)
    sdg_centroids = np.load(SDG_CENTROIDS).astype(np.float32)
    baseline_unit = sdg_centroids[SDG17_IDX]
    semgap_payload = load_json(layout.data_dir / "sdg_conceptual_alignment_cosine_distances.json")
    baseline_row = semgap_payload["per_sdg"][SDG17_IDX]

    sdg17_indices = [idx for idx, row in enumerate(benchmark_ids) if int(row["sdg"]) == SDG17]
    if len(sdg17_indices) == 0:
        raise RuntimeError("No SDG 17 benchmark texts found.")
    ref_embeddings = benchmark_emb[sdg17_indices]
    if ref_embeddings.shape[0] != 31:
        log.warning("Expected 31 SDG 17 benchmark texts, found %s", ref_embeddings.shape[0])

    weights, centroid_cos = bootstrap_reference_weights(
        ref_embeddings=ref_embeddings,
        baseline_unit=baseline_unit,
        draws=args.draws,
        seed=args.seed,
    )

    aligned_shards = load_aligned_research_shards()
    research_sums, research_counts = aggregate_research_sdg17_clusters(
        shards=aligned_shards,
        ref_embeddings=ref_embeddings,
        weights=weights,
        block_size=args.block_size,
    )

    if np.any(research_counts < MIN_CLUSTER_SIZE):
        n_bad = int(np.sum(research_counts < MIN_CLUSTER_SIZE))
        raise RuntimeError(f"{n_bad} SDG 17 bootstrap draws fell below MIN_CLUSTER_SIZE on the research side.")

    research_units = np.zeros_like(research_sums, dtype=np.float32)
    for idx in range(args.draws):
        raw = research_sums[idx] / float(research_counts[idx])
        norm = float(np.linalg.norm(raw))
        if norm < 1e-8:
            raise RuntimeError(f"Draw {idx + 1}: near-zero SDG 17 research centroid.")
        research_units[idx] = (raw / norm).astype(np.float32)

    policy_emb = np.load(POLICY_EMB).astype(np.float32)
    policy_scores = np.load(POLICY_SCORES).astype(np.float32)
    policy_ids = load_json(POLICY_IDS)
    policy_rows = compute_policy_rows(
        ref_embeddings=ref_embeddings,
        weights=weights,
        policy_emb=policy_emb,
        policy_scores=policy_scores,
        policy_ids=policy_ids,
        research_units=research_units,
        research_counts=research_counts,
        seed=args.seed,
    )

    valid_rows = [row for row in policy_rows if not row["unreliable"] and row["semantic_gap"] is not None]
    if len(valid_rows) != args.draws:
        raise RuntimeError(
            f"Expected {args.draws} valid SDG 17 bootstrap rows, found {len(valid_rows)}. "
            "This appendix diagnostic is not designed for sparse-cluster failure."
        )

    draw_rows: list[dict[str, Any]] = []
    for draw_idx, row in enumerate(valid_rows):
        draw_rows.append(
            {
                "draw": int(row["draw"]),
                "centroid_cosine_to_baseline": round(float(centroid_cos[draw_idx]), 6),
                "semantic_similarity": row["semantic_similarity"],
                "semantic_gap": row["semantic_gap"],
                "n_research_papers": int(row["n_research_papers"]),
                "n_policy_chunks": int(row["n_policy_chunks"]),
                "n_policy_chunks_capped": int(row["n_policy_chunks_capped"]),
                "n_policy_docs": int(row["n_policy_docs"]),
                "n_policy_docs_capped": int(row["n_policy_docs_capped"]),
                "policy_cohesion": row["policy_cohesion"],
            }
        )

    gap_values = np.array([float(row["semantic_gap"]) for row in draw_rows], dtype=np.float64)
    research_n_values = np.array([int(row["n_research_papers"]) for row in draw_rows], dtype=np.int64)
    policy_doc_values = np.array([int(row["n_policy_docs_capped"]) for row in draw_rows], dtype=np.int64)

    summary = {
        "generated_from": "code/3_main_analysis/3_appendix/6_sdg17_reference_sensitivity.py",
        "note": (
            "This is a conditional bootstrap reference-set sensitivity check for SDG 17. "
            "It does not replace the canonical semantic-gap estimate and should not be read as "
            "a formal inferential confidence interval over substantive SDG 17 reality."
        ),
        "benchmark_n": int(ref_embeddings.shape[0]),
        "draws": int(args.draws),
        "chunk_cap": CHUNK_CAP_PRIMARY,
        "min_cluster_size": MIN_CLUSTER_SIZE,
        "baseline": {
            "semantic_gap": float(baseline_row["semantic_gap"]),
            "semantic_similarity": float(baseline_row["semantic_similarity"]),
            "n_research_papers": int(baseline_row["n_papers"]),
            "n_policy_docs_capped": int(baseline_row["n_policy_docs_capped"]),
        },
        "bootstrap": {
            "centroid_cosine_to_baseline": summarise_numeric(centroid_cos.astype(np.float64)),
            "semantic_gap": summarise_numeric(gap_values),
            "n_research_papers": summarise_numeric(research_n_values.astype(np.float64)),
            "n_policy_docs_capped": summarise_numeric(policy_doc_values.astype(np.float64)),
        },
    }

    write_csv(
        out_dir / DRAWS_CSV,
        [
            "draw",
            "centroid_cosine_to_baseline",
            "semantic_similarity",
            "semantic_gap",
            "n_research_papers",
            "n_policy_chunks",
            "n_policy_chunks_capped",
            "n_policy_docs",
            "n_policy_docs_capped",
            "policy_cohesion",
        ],
        draw_rows,
    )
    (out_dir / SUMMARY_JSON).write_text(json.dumps(summary, indent=2), encoding="utf-8")
    write_num_tex(layout.tables_dir / NUM_TEX, summary)
    write_table(layout.tables_dir / TABLE_TEX, summary)

    log.info("Saved: %s", out_dir / DRAWS_CSV)
    log.info("Saved: %s", out_dir / SUMMARY_JSON)
    log.info("Saved: %s", layout.tables_dir / NUM_TEX)
    log.info("Saved: %s", layout.tables_dir / TABLE_TEX)


if __name__ == "__main__":
    main()
