"""
Export reference-corpus split sizes from training outputs to a num_*.tex macro
file for use in the main text and Appendix D prose.

Reads sdg_retrain_results.json from
2_data/4_supervised_model_results/{model}/model/ and writes
num17_reference_split.tex into 4_outputs/main/{model}/tables/.
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[3]
CODE_ROOT = ROOT / "1_code"
SHARED_DIR = Path(__file__).resolve().parents[1] / "0_shared"
for path in (CODE_ROOT, SHARED_DIR):
    if str(path) not in sys.path:
        sys.path.insert(0, str(path))

from model_utils import DEFAULT_EMBED_MODEL, model_results_dir_for_model, resolve_model_alias
from shared_utils import ensure_canonical_outputs, fingerprint_of, should_skip, record_fingerprint


def latex_int(value: int) -> str:
    """Format an integer with LaTeX thousands-separator spacing."""
    s = f"{value:,}"
    return s.replace(",", "{,}")


def run(model: str, output_dir: Path, overwrite: bool = False) -> None:
    outs = ensure_canonical_outputs(output_dir, model=model)
    model_dir = model_results_dir_for_model(model) / "model"

    retrain_path = model_dir / "sdg_retrain_results.json"
    if not retrain_path.exists():
        print(
            f"sdg_retrain_results.json not found at {retrain_path}. "
            "Run 2_retrain_full_data.py first.",
            file=sys.stderr,
        )
        sys.exit(1)

    SCRIPT_VERSION = "1"
    PRIMARY = outs.tables_dir / "num17_reference_split.tex"
    OUTPUTS = [PRIMARY]
    fp = fingerprint_of(retrain_path) + SCRIPT_VERSION
    if should_skip(OUTPUTS, fp, overwrite, PRIMARY):
        print(f"Skipping {PRIMARY} \u2014 inputs unchanged")
        return

    with open(retrain_path) as f:
        data = json.load(f)

    n_train = data["data"]["n_train"]
    n_test = data["data"]["n_test"]
    n_total = n_train + n_test

    lines = [
        "% Auto-generated by 1_code/7_main_analysis/2_appendix/"
        "c0_export_corpus_split_sizes.py -- do not edit manually",
        rf"\newcommand{{\NReferencePool}}{{{latex_int(n_total)}}}",
        rf"\newcommand{{\NTrainPool}}{{{latex_int(n_train)}}}",
        rf"\newcommand{{\NTestPool}}{{{latex_int(n_test)}}}",
    ]

    path = outs.tables_dir / "num17_reference_split.tex"
    path.write_text("\n".join(lines) + "\n")
    print(f"Written {path}")
    record_fingerprint(OUTPUTS, fp, PRIMARY)


def parse_args(argv=None):
    parser = argparse.ArgumentParser()
    parser.add_argument("--embed-model", default=DEFAULT_EMBED_MODEL, type=resolve_model_alias)
    parser.add_argument("--output-dir", type=Path, required=True)
    parser.add_argument("--overwrite", action="store_true", help=argparse.SUPPRESS)
    return parser.parse_args(argv)


def main():
    args = parse_args()
    run(args.embed_model, args.output_dir, overwrite=args.overwrite)


if __name__ == "__main__":
    main()
