"""
Export grid-search CV macro-F1 values from training outputs to a num_*.tex
macro file for use in Appendix D prose.

Reads lr_cv_results.json and mlp_cv_results.json from
2_data/4_supervised_model_results/{model}/model/ and writes
num_model_selection.tex into 4_outputs/main/{model}/tables/.
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[3]
CODE_ROOT = ROOT / "1_code"
SHARED_DIR = Path(__file__).resolve().parents[1] / "0_shared"
for path in (CODE_ROOT, SHARED_DIR):
    if str(path) not in sys.path:
        sys.path.insert(0, str(path))

from model_utils import DEFAULT_EMBED_MODEL, model_results_dir_for_model
from shared_utils import ensure_canonical_outputs


def run(model: str, output_dir: Path) -> None:
    outs = ensure_canonical_outputs(output_dir, model=model)
    model_dir = model_results_dir_for_model(model) / "model"

    lr_path = model_dir / "lr_cv_results.json"
    mlp_path = model_dir / "mlp_cv_results.json"

    if not lr_path.exists() or not mlp_path.exists():
        print(
            f"CV results JSONs not found in {model_dir}. "
            "Run 1_train_models_LR.py and 1_train_models_MLP.py first.",
            file=sys.stderr,
        )
        sys.exit(1)

    with open(lr_path) as f:
        lr = json.load(f)
    with open(mlp_path) as f:
        mlp = json.load(f)

    lines = [
        "% Auto-generated by 1_code/7_main_analysis/2_appendix/"
        "d1_export_model_selection_nums.py -- do not edit manually",
        rf"\newcommand{{\LrCvMacroFone}}{{{lr['best_cv_macro_f1_mean']:.4f}}}",
        rf"\newcommand{{\LrCvMacroFoneStd}}{{{lr['best_cv_macro_f1_std']:.4f}}}",
        rf"\newcommand{{\MlpCvMacroFone}}{{{mlp['best_cv_macro_f1_mean']:.4f}}}",
        rf"\newcommand{{\MlpCvMacroFoneStd}}{{{mlp['best_cv_macro_f1_std']:.4f}}}",
    ]

    path = outs.tables_dir / "num_model_selection.tex"
    path.write_text("\n".join(lines) + "\n")
    print(f"Written {path}")


def parse_args(argv=None):
    parser = argparse.ArgumentParser()
    parser.add_argument("--embed-model", default=DEFAULT_EMBED_MODEL)
    parser.add_argument("--output-dir", type=Path, required=True)
    return parser.parse_args(argv)


def main():
    args = parse_args()
    run(args.embed_model, args.output_dir)


if __name__ == "__main__":
    main()
