"""
Export grid-search CV macro-F1 values from training outputs to a num_*.tex
macro file for use in Appendix D prose.

Reads lr_cv_results.json and grid_search_log.json from
2_data/4_supervised_model_results/{model}/model/ and writes
num_model_selection.tex into 4_outputs/main/{model}/tables/.
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[3]
CODE_ROOT = ROOT / "1_code"
SHARED_DIR = Path(__file__).resolve().parents[1] / "0_shared"
for path in (CODE_ROOT, SHARED_DIR):
    if str(path) not in sys.path:
        sys.path.insert(0, str(path))

from model_utils import DEFAULT_EMBED_MODEL, model_results_dir_for_model
from shared_utils import ensure_canonical_outputs


def run(model: str, output_dir: Path) -> None:
    outs = ensure_canonical_outputs(output_dir, model=model)
    model_dir = model_results_dir_for_model(model) / "model"

    # --- LR ---
    lr_path = model_dir / "lr_cv_results.json"
    if not lr_path.exists():
        print(f"LR CV results not found at {lr_path}. Run 1_train_models_LR.py first.", file=sys.stderr)
        sys.exit(1)
    with open(lr_path) as f:
        lr = json.load(f)

    lr_best_mean = lr["best_cv_macro_f1_mean"]
    lr_best_std = lr["best_cv_macro_f1_std"]

    lr_c1 = None
    for r in lr["all_cv_results"]:
        if r["params"]["C"] == 1.0:
            lr_c1 = r
            break
    if lr_c1 is None:
        print("LR C=1 config not found in lr_cv_results.json", file=sys.stderr)
        sys.exit(1)
    lr_c1_mean = lr_c1["mean_f1"]
    lr_c1_std = lr_c1["std_f1"]

    # --- MLP grid search ---
    gs_path = model_dir / "grid_search_log.json"
    if not gs_path.exists():
        print(f"Grid search log not found at {gs_path}. Run 1_train_models_MLP.py first.", file=sys.stderr)
        sys.exit(1)
    with open(gs_path) as f:
        gs = json.load(f)

    seen = {}
    for entry in gs.get("log", []):
        cfg = entry.get("config", {})
        if "n_layers" not in cfg:
            continue
        key = (cfg["n_layers"], cfg["hidden_size"], cfg["lr"])
        if key not in seen:
            seen[key] = entry["cv_metrics"]

    sorted_mlp = sorted(seen.items(), key=lambda kv: (-kv[1]["mean_f1"], kv[0][0], kv[0][1], kv[0][2]))

    best_mlp_key, best_mlp = sorted_mlp[0]
    mlp_best_mean = best_mlp["mean_f1"]
    mlp_best_std = best_mlp["std_f1"]

    best_nl, best_hs = best_mlp_key[0], best_mlp_key[1]
    rank2_entry = None
    for k, v in sorted_mlp:
        if (k[0], k[1]) != (best_nl, best_hs):
            rank2_entry = (k, v)
            break
    if rank2_entry is None:
        print("No rank-2 entry found in grid search log", file=sys.stderr)
        sys.exit(1)
    mlp_rank2_mean = rank2_entry[1]["mean_f1"]
    mlp_rank2_std = rank2_entry[1]["std_f1"]

    gap = mlp_best_mean - lr_best_mean

    mlp_2l_4l_vals = [v["mean_f1"] for (nl, hs, lr), v in seen.items() if nl in {2, 4}]
    mlp_8l_16l_vals = [v["mean_f1"] for (nl, hs, lr), v in seen.items() if nl in {8, 16}]
    range_2l_4l = f"{min(mlp_2l_4l_vals):.3f}--{max(mlp_2l_4l_vals):.3f}"
    range_8l_16l = f"{min(mlp_8l_16l_vals):.3f}--{max(mlp_8l_16l_vals):.3f}"

    lines = [
        "% Auto-generated by 1_code/7_main_analysis/2_appendix/"
        "d1_export_model_selection_nums.py -- do not edit manually",
        rf"\newcommand{{\LrCvMacroFone}}{{{lr_best_mean:.4f}}}",
        rf"\newcommand{{\LrCvMacroFoneStd}}{{{lr_best_std:.4f}}}",
        rf"\newcommand{{\LrCvMacroFoneCOne}}{{{lr_c1_mean:.4f}}}",
        rf"\newcommand{{\LrCvMacroFoneCOneStd}}{{{lr_c1_std:.4f}}}",
        rf"\newcommand{{\MlpCvMacroFone}}{{{mlp_best_mean:.4f}}}",
        rf"\newcommand{{\MlpCvMacroFoneStd}}{{{mlp_best_std:.4f}}}",
        rf"\newcommand{{\MlpCvMacroFoneFourLTwoFiftySixH}}{{{mlp_rank2_mean:.4f}}}",
        rf"\newcommand{{\MlpCvMacroFoneFourLTwoFiftySixHStd}}{{{mlp_rank2_std:.4f}}}",
        rf"\newcommand{{\LrMlpGap}}{{{gap:.4f}}}",
        rf"\newcommand{{\MlpCvRangeTwoLFourL}}{{{range_2l_4l}}}",
        rf"\newcommand{{\MlpCvRangeEightLSixteenL}}{{{range_8l_16l}}}",
    ]

    path = outs.tables_dir / "num_model_selection.tex"
    path.write_text("\n".join(lines) + "\n")
    print(f"Written {path}")


def parse_args(argv=None):
    parser = argparse.ArgumentParser()
    parser.add_argument("--embed-model", default=DEFAULT_EMBED_MODEL)
    parser.add_argument("--output-dir", type=Path, required=True)
    return parser.parse_args(argv)


def main():
    args = parse_args()
    run(args.embed_model, args.output_dir)


if __name__ == "__main__":
    main()
