"""Export policy-subcorpus and reference single-label counts as LaTeX macros.

Reads the segmented policy/reference JSONL (derived from the frozen snapshot) and
emits 4_outputs/mpnet/tables/num19_policy_subcorpus.tex with \newcommand macros so the
Methodology text stays macro-driven (no hardcoded pipeline-computed numbers).

Counts verified to match the committed manuscript:
  curated_ai_sdg  : 13,123 segments / 94 documents
  sdgi_vnr_vlr    : 21,346 segments / 4,225 documents (at segmentation)
  ungdc_speeches  : 6,128 segments / 2,048 documents
  SDGi single-label reference texts: 20,267
"""
from __future__ import annotations

import json
import logging
from collections import defaultdict
from pathlib import Path

SEGMENTED = Path("2_data/2_segmented")
OUT = Path("4_outputs/mpnet/tables/num19_policy_subcorpus.tex")

log = logging.getLogger(__name__)


def _tex_int(n) -> str:
    if isinstance(n, int):
        s = f"{n:,}"
        return s.replace(",", "{,}")
    return "---"


def main() -> None:
    # --- policy sub-corpus counts (segments + distinct source_doc per source_family) ---
    # Degrade to "---" (not a hard crash) when 2_segmented/ is absent — this
    # script's num19 output is retired (folded into num18) and is never a warm/
    # cold replay step, but a manual run on a fresh clone must not raise.
    pol_fam = defaultdict(lambda: [0, set()])
    seg_policy = SEGMENTED / "policy.jsonl"
    try:
        with open(seg_policy) as f:
            for line in f:
                o = json.loads(line)
                sf = o.get("source_family")
                pol_fam[sf][0] += 1
                pol_fam[sf][1].add(o.get("source_doc"))
    except FileNotFoundError:
        log.warning("policy.jsonl not found: %s (fresh clone?) emitting '---' macros", seg_policy)

    curated_seg = curated_doc = sdgi_seg = sdgi_doc = ungdc_seg = ungdc_doc = None
    if seg_policy.exists():
        curated_seg, curated_doc_set = pol_fam["curated_ai_sdg"]
        curated_doc = len(curated_doc_set)
        sdgi_seg, sdgi_doc_set = pol_fam["sdgi_vnr_vlr"]
        sdgi_doc = len(sdgi_doc_set)
        ungdc_seg, ungdc_doc_set = pol_fam["ungdc_speeches"]
        ungdc_doc = len(ungdc_doc_set)

    # --- SDGi single-label reference texts (sdgs is a length-1 list) ---
    ref_path = SEGMENTED / "reference.jsonl"
    sdgi_single = None
    if ref_path.exists():
        with open(ref_path) as f:
            for line in f:
                o = json.loads(line)
                if o.get("source") == "sdgi":
                    L = o.get("sdgs")
                    if isinstance(L, list) and len(L) == 1:
                        sdgi_single += 1
    else:
        log.warning("reference.jsonl not found: %s (fresh clone?) sdgi_single='---'", ref_path)

    macros = [
        ("PolicyCuratedSegments", curated_seg),
        ("PolicyCuratedDocs", curated_doc),
        ("PolicySDGiSegAtSeg", sdgi_seg),
        ("PolicySDGiDocsAtSeg", sdgi_doc),
        ("PolicySDGiSingleLabel", sdgi_single),
        ("PolicyUNGDCSegments", ungdc_seg),
        ("PolicyUNGDCDocs", ungdc_doc),
    ]

    lines = [
        "% Auto-generated by 1_code/7_main_analysis/2_appendix/export_policy_subcorpus_counts.py -- do not edit manually",
    ]
    for name, val in macros:
        lines.append(f"\\newcommand{{\\{name}}}{{{_tex_int(val)}}}")

    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text("\n".join(lines) + "\n")
    print("wrote", OUT)
    for name, val in macros:
        print(f"  \\{name} = {_tex_int(val)}")


if __name__ == "__main__":
    main()
