"""Export policy-subcorpus and reference single-label counts as LaTeX macros.

Reads the segmented policy/reference JSONL (derived from the frozen snapshot) and
emits 4_outputs/mpnet/tables/num19_policy_subcorpus.tex with \newcommand macros so the
Methodology text stays macro-driven (no hardcoded pipeline-computed numbers).

Counts verified to match the committed manuscript:
  curated_ai_sdg  : 13,123 segments / 94 documents
  sdgi_vnr_vlr    : 21,346 segments / 4,225 documents (at segmentation)
  ungdc_speeches  : 6,128 segments / 2,048 documents
  SDGi single-label reference texts: 20,267
"""
from __future__ import annotations

import json
from collections import defaultdict
from pathlib import Path

SEGMENTED = Path("2_data/2_segmented")
OUT = Path("4_outputs/mpnet/tables/num19_policy_subcorpus.tex")


def _tex_int(n: int) -> str:
    s = f"{n:,}"
    return s.replace(",", "{,}")


def main() -> None:
    # --- policy sub-corpus counts (segments + distinct source_doc per source_family) ---
    pol_fam = defaultdict(lambda: [0, set()])
    with open(SEGMENTED / "policy.jsonl") as f:
        for line in f:
            o = json.loads(line)
            sf = o.get("source_family")
            pol_fam[sf][0] += 1
            pol_fam[sf][1].add(o.get("source_doc"))

    curated_seg, curated_doc_set = pol_fam["curated_ai_sdg"]
    curated_doc = len(curated_doc_set)
    sdgi_seg, sdgi_doc_set = pol_fam["sdgi_vnr_vlr"]
    sdgi_doc = len(sdgi_doc_set)
    ungdc_seg, ungdc_doc_set = pol_fam["ungdc_speeches"]
    ungdc_doc = len(ungdc_doc_set)

    # --- SDGi single-label reference texts (sdgs is a length-1 list) ---
    sdgi_single = 0
    with open(SEGMENTED / "reference.jsonl") as f:
        for line in f:
            o = json.loads(line)
            if o.get("source") == "sdgi":
                L = o.get("sdgs")
                if isinstance(L, list) and len(L) == 1:
                    sdgi_single += 1

    macros = [
        ("PolicyCuratedSegments", curated_seg),
        ("PolicyCuratedDocs", curated_doc),
        ("PolicySDGiSegAtSeg", sdgi_seg),
        ("PolicySDGiDocsAtSeg", sdgi_doc),
        ("PolicySDGiSingleLabel", sdgi_single),
        ("PolicyUNGDCSegments", ungdc_seg),
        ("PolicyUNGDCDocs", ungdc_doc),
    ]

    lines = [
        "% Auto-generated by 1_code/7_main_analysis/2_appendix/export_policy_subcorpus_counts.py -- do not edit manually",
    ]
    for name, val in macros:
        lines.append(f"\\newcommand{{\\{name}}}{{{_tex_int(val)}}}")

    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text("\n".join(lines) + "\n")
    print("wrote", OUT)
    for name, val in macros:
        print(f"  \\{name} = {val:,}")


if __name__ == "__main__":
    main()
