"""
Export cross-encoder INLP convergence macros from the existing register
checkpoints to a num_*.tex macro file for the merged Appendix F prose.

CHEAP BY DESIGN: this script only reads the three register checkpoints that
register_adjust.py already persisted to 2_data/3b_register/{slug}/{track}/
during the normal pipeline. It does NOT re-run the INLP procedure or any other
analysis stage. Run it whenever the checkpoints change; fingerprints gate the
output so it re-derives only when an input moves.

Reads:
  2_data/3b_register/{mpnet,minilm,scibert}/{canon,subset}/checkpoint.json
Writes:
  4_outputs/mpnet/tables/num12b_register_cross_config.tex
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[3]
CODE_ROOT = ROOT / "1_code"
SHARED_DIR = Path(__file__).resolve().parents[1] / "0_shared"
for path in (CODE_ROOT, SHARED_DIR):
    if str(path) not in sys.path:
        sys.path.insert(0, str(path))

from model_utils import (
    DEFAULT_EMBED_MODEL,
    model_slug,
    register_dir_for_model,
    resolve_model_alias,
)
from shared_utils import (
    ensure_canonical_outputs,
    fingerprint_of,
    record_fingerprint,
    should_skip,
)

# (canonical model id, track) for the three encoder tracks that run INLP in
# warm/cold replay. Order is fixed: [mpnet, minilm, scibert].
TRACKS = [
    ("all-mpnet-base-v2", "canon"),
    ("all-MiniLM-L6-v2", "subset"),
    ("allenai/scibert_scivocab_uncased", "subset"),
]


def _load_iterations(model: str, track: str) -> list[dict]:
    ckpt = register_dir_for_model(model) / track / "checkpoint.json"
    if not ckpt.exists():
        raise FileNotFoundError(
            f"Register checkpoint not found at {ckpt}. "
            "Run the register_adjust stage (INLP) for all three encoder tracks first."
        )
    with open(ckpt) as f:
        data = json.load(f)
    iterations = data.get("iterations")
    if not iterations:
        raise ValueError(f"No 'iterations' in {ckpt}")
    return iterations


def _track_stats(model: str, track: str) -> dict:
    its = _load_iterations(model, track)
    iter1_acc = float(its[0]["test_acc"])
    final_acc = float(its[-1]["test_acc"])
    n_iters = int(its[-1]["k"])
    # k=15 is the cross-track comparison point: every INLP track currently
    # completes well past 15 iterations before its data-dependent stop, so
    # the entry exists in every checkpoint. If a future track stops earlier,
    # the nan fallback below silently prints the literal text "nan" into
    # num12b — fail loudly instead of relying on it.
    acc_at_15 = next((float(r["test_acc"]) for r in its if r["k"] == 15), float("nan"))
    return {
        "model": model,
        "track": track,
        "iter1_acc": iter1_acc,
        "final_acc": final_acc,
        "n_iters": n_iters,
        "acc_at_15": acc_at_15,
    }


def run(model: str, output_dir: Path, overwrite: bool = False) -> None:
    outs = ensure_canonical_outputs(output_dir, model=model)

    try:
        stats = [_track_stats(m, t) for m, t in TRACKS]
    except (FileNotFoundError, ValueError) as e:
        print(str(e), file=sys.stderr)
        sys.exit(1)

    primary = outs.tables_dir / "num12b_register_cross_config.tex"
    outputs = [primary]
    ckpts = [register_dir_for_model(m) / t / "checkpoint.json" for m, t in TRACKS]
    fp = fingerprint_of(*ckpts) + "v1"
    if should_skip(outputs, fp, overwrite, primary):
        print(f"Skipping {primary} — inputs unchanged")
        return

    first = [s["iter1_acc"] for s in stats]
    final = [s["final_acc"] for s in stats]
    at15 = [s["acc_at_15"] for s in stats]

    # stats order matches TRACKS: [mpnet, minilm, scibert].
    mpnet, minilm, scibert = stats

    lines = [
        "% Auto-generated by 2_appendix/f2_export_register_cross_config.py "
        "-- reads existing register checkpoints; do not edit manually",
        rf"\newcommand{{\RegisterCrossFirstAccMin}}{{{min(first):.3f}}}",
        rf"\newcommand{{\RegisterCrossFirstAccMax}}{{{max(first):.3f}}}",
        rf"\newcommand{{\RegisterCrossFinalAccMin}}{{{min(final):.3f}}}",
        rf"\newcommand{{\RegisterCrossFinalAccMax}}{{{max(final):.3f}}}",
        rf"\newcommand{{\RegisterCrossAccAtFifteenMin}}{{{min(at15):.3f}}}",
        rf"\newcommand{{\RegisterCrossAccAtFifteenMax}}{{{max(at15):.3f}}}",
        rf"\newcommand{{\RegisterCrossMpnetIters}}{{{mpnet['n_iters']}}}",
        rf"\newcommand{{\RegisterCrossMpnetFinalAcc}}{{{mpnet['final_acc']:.3f}}}",
        rf"\newcommand{{\RegisterCrossMinilmIters}}{{{minilm['n_iters']}}}",
        rf"\newcommand{{\RegisterCrossMinilmFinalAcc}}{{{minilm['final_acc']:.3f}}}",
        rf"\newcommand{{\RegisterCrossScibertIters}}{{{scibert['n_iters']}}}",
        rf"\newcommand{{\RegisterCrossScibertFinalAcc}}{{{scibert['final_acc']:.3f}}}",
    ]

    primary.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"Written {primary}")
    record_fingerprint(outputs, fp, primary)


def parse_args(argv=None):
    parser = argparse.ArgumentParser()
    parser.add_argument("--embed-model", default=DEFAULT_EMBED_MODEL, type=resolve_model_alias)
    parser.add_argument("--output-dir", type=Path, required=True)
    parser.add_argument("--overwrite", action="store_true", help=argparse.SUPPRESS)
    return parser.parse_args(argv)


def main():
    args = parse_args()
    run(args.embed_model, args.output_dir, overwrite=args.overwrite)


if __name__ == "__main__":
    main()
