"""
Export the combined cross-encoder iterative register-removal diagnostic table.

Reads the three register checkpoints (canon for MPNet, subset for MiniLM/SciBERT,
by design) and writes a single wide LaTeX table covering all three encoder tracks:
    It. | MPNet (acc, gap, p vs raw) | MiniLM (...) | SciBERT (...)

This is the expanded version of Table 12 (tab:iterative-register-check) that the
per-model `g_register_decomposition.py` only emits for MPNet.  The Spearman
column is the rank correlation of each track's per-SDG gap vector at iteration k
versus that track's *raw* (iteration 0, un-projected) gap vector — consistent
with the per-model diagnostic and the Appendix G.1 prose.

CHEAP-ISH BY DESIGN: no re-training.  It reuses `_compute_iterative_rows` from
`0_shared/g_register_decomposition.py`, which only reads the persisted G.npy /
checkpoint.json and the policy/research embeddings.  Fingerprint-gated so it
re-derives only when an input moves.

Outputs:
   4_outputs/mpnet/tables/tab12_register_cross.tex
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[3]
CODE_ROOT = ROOT / "1_code"
SHARED_DIR = Path(__file__).resolve().parents[1] / "0_shared"
for path in (CODE_ROOT, SHARED_DIR):
    if str(path) not in sys.path:
        sys.path.insert(0, str(path))

from model_utils import DEFAULT_EMBED_MODEL, resolve_model_alias
from register_utils import register_dir
from shared_utils import (
    ensure_canonical_outputs,
    fingerprint_of,
    record_fingerprint,
    should_skip,
)
from g_register_decomposition import _compute_iterative_rows

# (model, display label) — order is fixed: [mpnet, minilm, scibert].
TRACKS = [
    ("all-mpnet-base-v2", "MPNet"),
    ("all-MiniLM-L6-v2", "MiniLM"),
    ("allenai/scibert_scivocab_uncased", "SciBERT"),
]


def run(model: str, output_dir: Path, overwrite: bool = False) -> None:
    outs = ensure_canonical_outputs(output_dir, model=model)
    out_tex = outs.tables_dir / "tab12_register_cross.tex"

    ckpts = [register_dir(m) / "checkpoint.json" for m, _ in TRACKS]
    fp = fingerprint_of(*ckpts) + "cross_v1"
    if should_skip([out_tex], fp, overwrite, out_tex):
        print(f"Skipping {out_tex} — inputs unchanged")
        return

    tracks_data = []
    for m, label in TRACKS:
        try:
            rows, _summary, _G_full, _raw = _compute_iterative_rows(m)
        except (FileNotFoundError, RuntimeError, ValueError) as e:
            print(f"Skipping track {label} ({m}): {e}", file=sys.stderr)
            continue
        tracks_data.append((label, {r["k"]: r for r in rows if r.get("shown")}))

    if not tracks_data:
        print("No register checkpoints available — nothing to write.", file=sys.stderr)
        return

    all_ks = sorted(set().union(*[set(d.keys()) for _, d in tracks_data]))

    col_fmt = "l" + " rrr" * len(tracks_data)
    group_rules = " ".join(
        rf"\cmidrule(lr){{{2 + 3 * i}-{4 + 3 * i}}}" for i in range(len(tracks_data))
    )
    header_groups = " & ".join(rf"\multicolumn{{3}}{{c}}{{{label}}}" for label, _ in tracks_data)
    header_cols = " & ".join(["acc & gap & p vs raw"] * len(tracks_data))

    lines = [
        "% Auto-generated by 2_appendix/f3_register_iterative_cross_table.py",
        "% seed: 42 (PERMUTATION_SEED) — policy per-document cap sampling; do not edit manually",
        rf"\begin{{tabular}}{{{col_fmt}}}",
        r"\toprule",
        f"& {header_groups} \\\\",
        f"{group_rules}",
        rf"It. & {header_cols} \\",
        r"\midrule",
    ]

    for k in all_ks:
        cells = [str(k)]
        for _label, d in tracks_data:
            r = d.get(k)
            if r is None:
                cells += ["—", "—", "—"]
            else:
                mg = f"{r['mean_gap']:.3f}" if r.get("mean_gap") is not None else "—"
                sp = f"{r['rho_vs_raw']:.3f}" if r.get("rho_vs_raw") is not None else "—"
                cells += [f"{r['test_acc']:.3f}", mg, sp]
        lines.append(" & ".join(cells) + r" \\")

    lines += [r"\bottomrule", r"\end{tabular}"]

    out_tex.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"Written {out_tex}")
    record_fingerprint([out_tex], fp, out_tex)


def parse_args(argv=None):
    parser = argparse.ArgumentParser()
    parser.add_argument("--embed-model", default=DEFAULT_EMBED_MODEL, type=resolve_model_alias)
    parser.add_argument("--output-dir", type=Path, required=True)
    parser.add_argument("--overwrite", action="store_true", help=argparse.SUPPRESS)
    return parser.parse_args(argv)


def main():
    args = parse_args()
    run(args.embed_model, args.output_dir, overwrite=args.overwrite)


if __name__ == "__main__":
    main()
